require("basic")
require("keybindings")
require("plugins")
require("colorscheme")
require("autocmds")
-- plugins
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("plugin-config.indent-blankline")
-- require("plugin-config.toggleterm")
require("plugin-config.surround")
require("plugin-config.comment")
require("plugin-config.nvim-autopairs")
-- require("plugin-config.fidget")
-- lsp
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
-- format
require("lsp.formatter")
-- require("lsp.null-ls")
-- DAP
-- require("dap.vimspector")
-- require("dap.nvim-dap")
-- utils
-- require('utils.fix-yank')
