require "user.conf.nvim-treesitter"
require "user.conf.nvim-autopairs"
require "user.conf.comment"
require "user.conf.nvim-notify"
require "user.conf.toggleterm"
require "user.conf.filetype"
require "user.conf.lualine"
require "user.conf.telescope"
require "user.conf.gitsigns"

