require "user.conf.nvim-tree"
require "user.conf.nvim-treesitter"
require "user.conf.nvim-autopairs"
require "user.conf.comment"
require "user.conf.nvim-notify"
require "user.conf.toggleterm"
require "user.conf.filetype"
require "user.conf.lualine"
require "user.conf.telescope"
require "user.conf.nvim-cmp"
require "user.conf.project"
require "user.conf.gitsigns"
-- require "user.conf.github-nvim-theme"

